name: Copy published events from DICI.ca to Tourism Mauricie

on:
  workflow_dispatch:

jobs:
  update_footlight_cms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Footlight CMS
        uses: gr2m/http-request@v2.1.0
        with:
          url: https://api.cms.footlight.io/login
          method: POST
          headers: |
            Content-Type: application/json
          body: |
            {
              "email": "${{ vars.AGGREGATOR_USER_CULTURE_MAURICIE_2 }}",
              "password": "${{ secrets.AGGREGATOR_PASSWORD_CULTURE_MAURICIE_2  }}"
            }
        env:
          ACCESS_TOKEN: ${{ steps.login.outputs.response.body.accessToken }}

      - name: Update Calendar Mapping
        uses: gr2m/http-request@v2.1.0
        with:
          url: https://api.cms.footlight.io/entities/import/657199fea5ac3d006314ea92?mapping-file-url=https%3A%2F%2Fraw.githubusercontent.com%2Fculturecreates%2Ffootlight-aggregator%2Fmain%2Fdata%2Fdici-to-tourisme-mauricie-calendars-concepts-mapping.json
          method: PUT
          headers: |
            Authorization: Bearer ${{ env.ACCESS_TOKEN }}
            calendar-id: 661e5a8818a64f7829aeae24