name: Run Ville de Gatineau Aggregator

on:
  schedule:
    - cron: "0 7 * * 1" # Run at 3:00 AM ET every Thursday

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATA_DOG_CLIENT_TOKEN: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}
          envkey_ENABLING_LOG_TO_DATA_DOG: true
          file_name: .env
          fail_on_empty: false
      - name: Build Footlight Aggregator
        run: npm run build
      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js import:entities -u ${{secrets.AGGREGATOR_USER_GATINEAU}} -p ${{secrets.AGGREGATOR_PASSWORD_GATINEAU}} -s http://kg.artsdata.ca/culture-creates/footlight/gatineau-cloud -i https://api.cms.footlight.io -c 6308ef4a7f771f00431d939a -b 10 -m https://culturecreates.github.io/footlight-aggregator/data/ville-de-gatineau-cms-mapping.json
