name: Run Complexe Culturel Aggregator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # 3 am ET every day

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_DATA_DOG_CLIENT_TOKEN: ${{ secrets.DATA_DOG_CLIENT_TOKEN }} 
          envkey_ENABLING_LOG_TO_DATA_DOG: true 
          envkey_CMS_REFERER_HEADER: ${{ vars.CMS_REFERER_HEADER }} 
          file_name: .env 
          fail_on_empty: false
      - name: Build Footlight Aggregator
        run: npm run build
      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js import:entities -u ${{vars.AGGREGATOR_USER_COMPLEXE_CULTUREL}} -p ${{secrets.AGGREGATOR_PASSWORD_COMPLEXE_CULTUREL}} -s http://kg.artsdata.ca/culture-creates/footlight/complexeculturelfelixleclerc-com -i https://api.cms.footlight.io -c 657199fea5ac3d006314ea92 -b 5 -m https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/complexe-culturel-cms-mapping.json