name: Fetch LePoint Events

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *" # Run every day at 5am EST
  
jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
        cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
        aggregator_username: ${{ vars.AGGREGATOR_USER_LEPOINT }}
        source_url: http://kg.artsdata.ca/culture-creates/footlight/culturemauricie_lepointdevente-com
        footlight_base_url: https://api.cms.footlight.io
        footlight_calendar_id: 657199fea5ac3d006314ea92
        batch_size: 5
        mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/caligram-cms-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_LEPOINT }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}