name: Import artsdata-planet-scenesfrancophones/scenesfrancophones-ca (ArtsCultureNB)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 5" # Run at 6:00 AM ET every Thursday

jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
      cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
      aggregator_username: ${{ vars.AGGREGATOR_USER_SCENES_FRANCOPHONES }}
      source_url: http://kg.artsdata.ca/capacoa/artsdata-planet-scenesfrancophones/scenesfrancophones-ca
      footlight_base_url: https://api.cms.footlight.io
      footlight_calendar_id: artsculturenb
      batch_size: 5
      mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/scenesfrancophones-cms-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_SCENES_FRANCOPHONE }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
