name: Import footlight/maisondelaculture-ca

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 4" # Run at 2:00 AM ET every Thursday

jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
        cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
        aggregator_username: ${{ vars.AGGREGATOR_USER_SALLE_ODYSSEE }}
        source_url: http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca
        footlight_base_url: https://api.cms.footlight.io
        footlight_calendar_id: tout-culture
        batch_size: 5
        mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/salle-odyssee-cms-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_SALLE_ODYSSEE }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}