name: Import RDF to footlight CMS

on:
  workflow_dispatch:
    inputs:
      onto-refine-config-url:
        type: string
        description: Onto Refine project configuration URL. This configuration is used to transform data.
        required: true
      data-url:
        type: string
        description: The entity URL that provides the data.
        required: true
      destination-url:
        type: string
        description: footlight environment URL
        required: true
      mapping-file-url:
        type: string
        description: The mapping file url.
        required: true
      calendar-id:
        type: string
        description: Destination calendar id.
        required: true
      file-extension:
        type: string
        description: Extension for the file downloaded from data-url(xml, json)

jobs:
  transform-data-into-rdf:
    runs-on: ubuntu-latest
    container:
      image: ontotext/refine:1.2.1
      options: --user root
      ports:
        - 7333:7333
    steps:

      - name: Install requirements
        run: apk update && apk add curl && apk add util-linux

      - name: Run ontorefine server
        run: /opt/ontorefine/dist/bin/ontorefine &

      - name: Download data from the API
        run: |
          curl '${{inputs.data-url}}' >> entities.${{inputs.file-extension}}

      - name: Download project-configuration-file
        id: step-4
        run: | 
          curl '${{inputs.onto-refine-config-url}}' >> project-config.json

      - name: Transform json data to RDF
        run: |
          /opt/ontorefine/dist/bin/ontorefine-cli \
          transform entities.${{inputs.file-extension}} \
          -u http://localhost:7333 \
          --configurations project-config.json \
          -f json >> entities.ttl
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: entities
          path: ./entities.ttl
          retention-days: 1

  run-aggregator-and-import:
    needs: transform-data-into-rdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATA_DOG_CLIENT_TOKEN: ${{ secrets.DATA_DOG_CLIENT_TOKEN }} 
          envkey_ENABLING_LOG_TO_DATA_DOG: true 
          envkey_CMS_REFERER_HEADER: ${{ vars.CMS_REFERER_HEADER }} 
          file_name: .env 
          fail_on_empty: false

      - name: Build Footlight Aggregator
        run: npm run build

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: entities

      - name: cat entities
        run: cat /home/runner/work/footlight-aggregator/footlight-aggregator/entities.ttl

      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js  \
          import:rdf -u ${{vars.ADMIN_EMAIL_RDF_IMPORT}} -p ${{secrets.ADMIN_PASSWORD_RDF_IMPORT}} \
          -i ${{inputs.destination-url}} \
          -c ${{inputs.calendar-id}} \
          -r '/home/runner/work/footlight-aggregator/footlight-aggregator/entities.ttl'  \
          -m ${{inputs.mapping-file-url}}
