name: Run Footlight Aggregator and Import data to Signe Laval calendar

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build Footlight Aggregator
        run: npm run build
      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js import:entities -u ${{secrets.AGGREGATOR_USER_SIGNE_LAVAL}} -p ${{secrets.AGGREGATOR_PASSWORD_SIGNE_LAVAL}} -s http://kg.artsdata.ca/culture-creates/footlight/signelaval-com -i https://staging.api.cms.footlight.io -c 63457978637093005071a053

