name: Import artsdata-planet-evenko/place-bell

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 1,3"  # Run at 2:00 AM ET every Monday and Wednesday

jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
      cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
      aggregator_username: ${{ vars.AGGREGATOR_USER_PLACE_BELL }}
      source_url: http://kg.artsdata.ca/capacoa/artsdata-planet-evenko/place-bell
      footlight_base_url: https://api.cms.footlight.io
      footlight_calendar_id: signe-laval
      batch_size: 10
      mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/place-bell-cms-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_PLACE_BELL }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}
      AWS_SES_ACCESS_KEY: ${{ secrets.AWS_SES_ACCESS_KEY }}
      AWS_SES_SECRET_ACCESS_KEY: ${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}
   
