name: Run Footlight Aggregator and Import data to Ville De Gatineau

on:
  schedule:
    - cron: "0 7 * * 4" # Run at 1:00 PM every Thursday in Indian time

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build Footlight Aggregator
        run: npm run build
      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js import:entities -u ${{secrets.AGGREGATOR_USER_GATINEAU}} -p ${{secrets.AGGREGATOR_PASSWORD_GATINEAU}} -s http://kg.artsdata.ca/culture-creates/footlight/gatineau-cloud -i https://api.cms.footlight.io -c 6308ef4a7f771f00431d939a -b 50

