name: Run Tourisme Maurice(source - Culture Mauricie) Aggregator

on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 5 * * 4"  # Run at 1:00 AM ET every Thursday
jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
        cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
        aggregator_username: ${{ AGGREGATOR_USER_CULTURE_MAURICIE_2 }}
        source_url: http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/culture-mauricie-cms-events
        footlight_base_url: https://api.cms.footlight.io
        footlight_calendar_id: 661e5a8818a64f7829aeae24
        batch_size: 5
        mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/culture-mauricie-to-tourisme-mauricie-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_CULTURE_MAURICIE_2 }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}