name: Import footlight/complexeculturelfelixleclerc-com

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # 3 am ET every day

jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
      cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
      aggregator_username: ${{ vars.AGGREGATOR_USER_COMPLEXE_CULTUREL }}
      source_url: http://kg.artsdata.ca/culture-creates/footlight/complexeculturelfelixleclerc-com
      footlight_base_url: https://api.cms.footlight.io
      footlight_calendar_id: culture-mauricie
      batch_size: 5
      mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/complexe-culturel-cms-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_COMPLEXE_CULTUREL }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}
      AWS_SES_ACCESS_KEY: ${{ secrets.AWS_SES_ACCESS_KEY }}
      AWS_SES_SECRET_ACCESS_KEY: ${{ secrets.AWS_SES_SECRET_ACCESS_KEY }}
