name: Import footlight/festivoix-com to culture-mauricie

on:
  workflow_dispatch:
#  schedule:
#    - cron: "30 9 * * 2" # Runs at 09:30 UTC, only on Tuesday

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: 
          envkey_DATA_DOG_CLIENT_TOKEN: ${{ secrets.DATA_DOG_CLIENT_TOKEN }} 
          envkey_ENABLING_LOG_TO_DATA_DOG: true 
          envkey_CMS_REFERER_HEADER: ${{ vars.CMS_REFERER_HEADER }} 
          file_name: .env 
          fail_on_empty: false
      - name: Build Footlight Aggregator
        run: npm run build
      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js \
          import:entities -u ${{vars.AGGREGATOR_USER_FESTIVOIX_COM}} -p ${{secrets.AGGREGATOR_PASSWORD_FESTIVOIX_COM}} \
          -s http://kg.artsdata.ca/culture-creates/footlight/culture-mauricie_festivoix-com \
          -i https://api.cms.footlight.io \
          -c 657199fea5ac3d006314ea92 \
          -b 5 \
          -m https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/complexe-culturel-cms-mapping.json
