name: Import footlight/festivoix-com

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 2" # Runs at 09:30 UTC, only on Tuesday
jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
      cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
      aggregator_username: ${{ vars.AGGREGATOR_USER_FESTIVOIX_COM}}
      source_url: http://kg.artsdata.ca/culture-creates/footlight/culture-mauricie_festivoix-com
      footlight_base_url: https://api.cms.footlight.io
      footlight_calendar_id: 657199fea5ac3d006314ea92
      batch_size: 5
      mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/complexe-culturel-cms-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_FESTIVOIX_COM }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}