name: Run Salle Odyssee Aggregator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 4" # Run at 2:00 AM ET every Thursday

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with: |
          envkey_DATA_DOG_CLIENT_TOKEN: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}
          envkey_ENABLING_LOG_TO_DATA_DOG: true
          envkey_CMS_REFERER_HEADER: ${{ secrets.CMS_REFERER_HEADER }}
          file_name: .env
          fail_on_empty: false
      - name: Build Footlight Aggregator
        run: npm run build
      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js import:entities -u ${{secrets.AGGREGATOR_USER_SALLE_ODYSSEE}} -p ${{secrets.AGGREGATOR_PASSWORD_SALLE_ODYSSEE}} -s http://kg.artsdata.ca/culture-creates/footlight/maisondelaculture-ca -i https://api.cms.footlight.io -c 6308ef4a7f771f00431d939a -b 5 -m https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/salle-odyssee-cms-mapping.json

