name: Run Shawinigan Aggregator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */6 *'

jobs:
  transform-data-into-rdf:
    runs-on: ubuntu-latest
    container:
      image: ontotext/refine:1.2.1
      options: --user root
      ports:
        - 7333:7333
    steps:

      - name: Install requirements
        run: apk update && apk add curl && apk add util-linux

      - name: Run ontorefine server
        run: /opt/ontorefine/dist/bin/ontorefine &

      - name: Download data from the API
        run: |
          curl 'https://api.ticketacces.net/v1/showtimes?KeyID=CULTURESHAWI&KeySecret=wMalrXUtnFEMIK7PDENGbPxRfiGY&Domains=shawinigan.ticketacces.net&Language=fr' >> entities.xml

      - name: Download project-configuration-file
        id: step-4
        run: | 
          curl 'https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/ontorefine/shawinigan-ontorefine-project-configurations.json' >> project-config.json

      - name: Transform json data to RDF
        run: |
          /opt/ontorefine/dist/bin/ontorefine-cli \
          transform entities.xml \
          -u http://localhost:7333 \
          --configurations project-config.json \
          -f xml >> entities.ttl
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: entities
          path: ./entities.ttl
          retention-days: 1

  run-aggregator-and-import:
    needs: transform-data-into-rdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATA_DOG_CLIENT_TOKEN: ${{ secrets.DATA_DOG_CLIENT_TOKEN }} 
          envkey_ENABLING_LOG_TO_DATA_DOG: true 
          envkey_CMS_REFERER_HEADER: ${{ vars.CMS_REFERER_HEADER }} 
          file_name: .env 
          fail_on_empty: false

      - name: Build Footlight Aggregator
        run: npm run build

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: entities

      - name: cat entities
        run: cat /home/runner/work/footlight-aggregator/footlight-aggregator/entities.ttl

      - name: Import entities to footlight
        run: |
          node ./dist/main-commander.js  \
          import:rdf -u ${{vars.AGGREGATOR_USER_SHAWINIGAN}} -p ${{secrets.AGGREGATOR_PASSWORD_SHAWINIGAN}} \
          -i 'https://staging.api.cms.footlight.io' \
          -c 657199fea5ac3d006314ea92 \
          -r '/home/runner/work/footlight-aggregator/footlight-aggregator/entities.ttl'  \
          -m 'https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/shawinigan-cms-mapping.json'
