name: Import orion/capitol-nb-ca

on:
  workflow_dispatch:
  schedule:
  - cron: "0 7 * * 5" # Run at 5:00 AM ET every Thursday

jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
      cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
      aggregator_username: ${{ vars.AGGREGATOR_USER_CAPITOL_NB }}
      source_url: http://kg.artsdata.ca/capacoa/artsdata-orion/capitol-nb-ca
      footlight_base_url: https://api.cms.footlight.io # production
      footlight_calendar_id: 65eeaf8ebec01b0064312f94
      batch_size: 5
      mapping_file_url: https://raw.githubusercontent.com/culturecreates/footlight-aggregator/main/data/theplayhouse-cms-mapping.json
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_CAPITOL_NB }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}
