name: Run Trois Rivieres Aggregator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day

jobs:
  push-to-cms:
    uses: culturecreates/footlight-aggregator/.github/workflows/import-data-to-cms.yml@main
    with:
        cms_referer_header: ${{ vars.CMS_REFERER_HEADER }}
        aggregator_username: ${{ vars.AGGREGATOR_USER_TROIS_RIVIERES }}
        source_url: http://kg.artsdata.ca/culture-creates/footlight/tourisme-troisrivieres-com
        footlight_base_url: https://api.cms.footlight.io
        footlight_calendar_id: 661e5a8818a64f7829aeae24
        batch_size: 5
    secrets:
      aggregator_password: ${{ secrets.AGGREGATOR_PASSWORD_TROIS_RIVIERES }}
      datadog_token: ${{ secrets.DATA_DOG_CLIENT_TOKEN }}