name: Run Footlight Aggregator and Import data to Tout culture calendar

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build Footlight Aggregator
        run: npm run build
      - name: Import entities to footlight
        env:
          EMAIL: ${{ secrets.AGGREGATOR_USER_TOUT_CULTURE}}
          PASSWORD: ${{secrets.AGGREGATOR_PASSWORD_TOUT_CULTURE}}
          SOURCE: ${{ secrets.TOUT_CULTURE_SOURCE_URL}}
          FOOTLIGHT_BASE_URL: ${{ secrets.FOOTLIGHT_BASE_URL}}
          CALENDAR: ${{ secrets.CALENDAR}}
        run: |
          echo "${{secrets.AGGREGATOR_USER_TOUT_CULTURE}} -- ${{secrets.AGGREGATOR_PASSWORD_TOUT_CULTURE}} -- ${{secrets.TOUT_CULTURE_SOURCE_URL}} -- ${{secrets.FOOTLIGHT_BASE_URL}} -- ${{secrets.CALENDAR}}"
          node ./dist/main.js import:entities -u ${{secrets.AGGREGATOR_USER_TOUT_CULTURE}} -p ${{secrets.AGGREGATOR_PASSWORD_TOUT_CULTURE}} -s ${{secrets.TOUT_CULTURE_SOURCE_URL}} -i  ${{secrets.FOOTLIGHT_BASE_URL}} -c ${{secrets.CALENDAR}}
