name: Transform data using Onto Refine and upload to Artsdtaa

on:
  workflow_dispatch:

jobs:
  download-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download ontotext/refine
        run: |
          curl -L https://download.ontotext.com/owlim/aa8cbf12-ad2d-11ed-b6c3-42843b1b6b38/ontorefine-1.2.0-dist.zip -o onto-refine.zip

      - name: Unzip file
        run: unzip onto-refine.zip

      - name: Run the onto-refine service
        run: nohup ./ontorefine-1.2.0/bin/ontorefine &

      - name: Download open-api response
        run: |
          curl 'https://api.footlight.io/calendars/tout-culture/events?page=1&limit=10' >> events.json

      - name: Transform open-api response to
        run: ./ontorefine-1.2.0/bin/ontorefine-cli transform events.json -u http://localhost:7333 --configurations ./data/ontorefine/open-api-transform-project-configuration.json -f json >> events.ttl

      - name: Display file
        run: cat events.ttl

      - name: Upload to S3
        uses: aws-actions/amazon-s3-upload-action@v2
        with:
          access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          bucket: footlight-aggregator-pipeline-files
          region: ca-central-1
          file: events.ttl
          key: events/