name: Transform data using Onto Refine and upload to Artsdtaa

on:
  workflow_dispatch:

jobs:
  download-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download ontotext/refine
        run: |
          curl -L https://download.ontotext.com/owlim/aa8cbf12-ad2d-11ed-b6c3-42843b1b6b38/ontorefine-1.2.0-dist.zip -o onto-refine.zip

      - name: Unzip file
        run: unzip onto-refine.zip -d onto-refine

      - name: Run the onto-refine service
        run: ./onto-refine/bin/ontorefine

      - name: Create project test
        run: ./onto-refine/bin/ontorefine-cli create --help
